version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  commands:
    - pip3 install -r requirements.txt
    - pip3 install python3-sphinx

sphinx:
  fail_on_warning: false
  configuration: docs/source/conf.py

python:
  # Install our python package before building the docs
  install:
    - requirements: requirements.txt
    - method: pip
      path: .